on:
  push:
    branches: [develop, stage, prod]

jobs: 
  dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: littleworks-inc/gcp-cloud-run/.github/workflows/deployment.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'
    with: 
      environment: dev
      ref: ${{ github.sha }}
      PROJECT_ID: nomadic
      GAR_LOCATION: northamerica-northeast2
      REGION: northamerica-northeast2
      APP: gcpcli
    secrets:
      workload_identity_provider: ${{ secrets.workload_identity_provider }}
      service_account: ${{ secrets.service_account }}
  stage:
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: littleworks-inc/gcp-cloud-run/.github/workflows/deployment.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'
    with: 
      environment: dev
      PROJECT_ID: nomadic
      GAR_LOCATION: northamerica-northeast2
      REGION: northamerica-northeast2
      APP: gcpcli
      ref: ${{ github.sha }}
    secrets:
      workload_identity_provider: ${{ secrets.workload_identity_provider }}
      service_account: ${{ secrets.service_account }}
  prod: 
    if: ${{ github.ref == 'refs/heads/prod' || github.base_ref == 'prod' }}
    uses: littleworks-inc/gcp-cloud-run/.github/workflows/deployment.yml@main
    permissions:
      contents: 'read'
      id-token: 'write'
    with: 
      environment: dev
      PROJECT_ID: nomadic
      GAR_LOCATION: northamerica-northeast2
      REGION: northamerica-northeast2
      APP: gcpcli
      ref: ${{ github.sha }}
    secrets:
      workload_identity_provider: ${{ secrets.workload_identity_provider }}
      service_account: ${{ secrets.service_account }}